name: Test Project CI

on: 
  push: 
    branches: 
      -  ci/gitHubActionsWorkflow
  pull_request:
    branches: 
      - main
  workflow_dispatch: # this command allows manually triggering from GitHub Actions tab.

jobs: 
  build: 
    name: Build and tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # next step is optional, becasue command above is checking out code from current repo by default.
      with: 
        repository: ${{ github.repository }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '7.0.x' # you may use any version you like, but I'll recomed to use >= 5.
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no--restore # --no--retore used because we used it in step before.

    - name: Run tests
      run: dotnet test --no-build # --no-build used because we've build everything already in the step above.

