name: Test Project CI

on: 
  push: 
    branches: 
      -  main
  pull_request:
    branches: 
      - main
  workflow_dispatch: # this command allows manually triggering from GitHub Actions tab.

jobs: 
  build: 
    name: Build and tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: '7.0.x'

    - name: Install Chrome dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4
        sudo apt-get install -y google-chrome-stable
        google-chrome --version
        which google-chrome

    - name: Set up display
      run: |
        export DISPLAY=:99
        Xvfb :99 -ac &
      
    - name: Restore dependencies
      run: dotnet restore
      working-directory: TestProject/

    - name: Build
      run: dotnet build --no-restore
      working-directory: TestProject/

    - name: Run tests
      run: dotnet test --no-build 
      working-directory: TestProject/
